spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://localhost:3306/billim
    username: admin
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  profiles:
    include:
      - aws
      - email
      - import

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: fe-test

  datasource:
    url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    schema: classpath:h2/schema.sql
    data: classpath:h2/data.sql

  h2:
    console:
      enabled: true
      path: /h2-console

  jwt:
    secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK