spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

  redis:
    host: localhost
    port: 6379

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  profiles:
    include:
      - aws
      - datasource
      - email
      - import
      - security
      - oauth

logging:
  level:
    org.springframework.web.cors: INFO

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
    disable-swagger-default-url: true

---
spring:
  config:
    activate:
      on-profile: fe-test